CREATE TABLE IF NOT EXISTS `exam_exam_sessions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `exam_id` bigint unsigned NOT NULL,
  `paper_id` bigint unsigned NOT NULL,
  `student_id` bigint unsigned NOT NULL,
  `attempt_no` int NOT NULL DEFAULT 1,
  `status` varchar(20) NOT NULL DEFAULT 'in_progress',
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deadline_at` datetime DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `last_saved_at` datetime DEFAULT NULL,
  `last_question_id` bigint unsigned DEFAULT NULL,
  `focus_loss_count` int NOT NULL DEFAULT 0,
  `last_focus_loss_at` datetime DEFAULT NULL,
  `focus_loss_action_applied` tinyint(1) NOT NULL DEFAULT 0,
  `penalty_score` int NOT NULL DEFAULT 0,
  `force_zero_score` tinyint(1) NOT NULL DEFAULT 0,
  `client_ip` varchar(45) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_exam_exam_sessions_exam_student` (`exam_id`, `student_id`),
  KEY `idx_exam_exam_sessions_student_status` (`student_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
