CREATE TABLE IF NOT EXISTS `exam_exams` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `intro_html` longtext NULL,
  `enable_notice` tinyint(1) NOT NULL DEFAULT 0,
  `notice_html` longtext NULL,
  `paper_id` bigint unsigned DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `started_at` datetime DEFAULT NULL,
  `ended_at` datetime DEFAULT NULL,
  `attempt_limit` int NOT NULL DEFAULT 1,
  `deadline_strategy` varchar(30) NOT NULL DEFAULT 'force_close',
  `allow_view_score` tinyint(1) NOT NULL DEFAULT 0,
  `allow_view_paper` tinyint(1) NOT NULL DEFAULT 0,
  `allow_view_analysis` tinyint(1) NOT NULL DEFAULT 0,
  `show_question_score` tinyint(1) NOT NULL DEFAULT 1,
  `show_question_difficulty` tinyint(1) NOT NULL DEFAULT 1,
  `auto_fullscreen` tinyint(1) NOT NULL DEFAULT 0,
  `enable_focus_monitor` tinyint(1) NOT NULL DEFAULT 0,
  `focus_loss_limit` int NOT NULL DEFAULT 0,
  `focus_loss_action` varchar(30) NOT NULL DEFAULT 'none',
  `focus_loss_deduct_score` int NOT NULL DEFAULT 0,
  `exam_code` varchar(24) DEFAULT NULL,
  `monitor_slug` varchar(32) DEFAULT NULL,
  `monitor_password_hash` varchar(255) DEFAULT NULL,
  `monitor_password_ciphertext` varchar(255) DEFAULT NULL,
  `monitor_password_iv` varchar(255) DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exam_exams_exam_code` (`exam_code`),
  UNIQUE KEY `uk_exam_exams_monitor_slug` (`monitor_slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
